# Spring Cloud Gateway port
server:
  port: 80

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
#          uri: http://localhost:8080
          uri: lb://hidoldori-web:8080
          predicates:
            - Path=/hidoldori/**
          filters:
            - name: UserFilter
              args:
                baseMessage: Taeu UserFilter
                preLogger: true
                postLogger: true
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
#        - id: shop-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/shop/**
#          filters:
#            - name: ShopFilter
#              args:
#                baseMessage: Taeu ShopFilter
#                preLogger: true
#                postLogger: true