# Spring Cloud Gateway port
server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/fallback
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
#          uri: http://34.69.205.52:8080
          uri: lb://hidoldori-web
          predicates:
            - Path=/hidoldori/lab/hidoldori-web/test
          filters:
            - name: UserFilter
              args:
                baseMessage: Taeu UserFilter
                preLogger: true
                postLogger: true
#        - id: shop-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/shop/**
#          filters:
#            - name: ShopFilter
#              args:
#                baseMessage: Taeu ShopFilter
#                preLogger: true
#                postLogger: true